const express = require('express')
const router = express.Router()
const user = require('./modules/user')
const todo = require('./modules/todo')
const home = require('./modules/home')
const { authenticate } = require('../middleware/authenticate')
router.use('/users', user)
router.use('/todos', authenticate , todo)
router.use('/', authenticate, home)
module.exports = router
